:tada: Update to version 1.8 (build 20211002)
This is no rewrite from scratch, but changes a lot of the script's behavior. The scripts now run unprivileged and store files in '/usr/local/acme'. The 'account.key' is now expected in '/etc/acme', as well as a new 'config.env' file that allows some basic configuration (like using another CA and setting a contact email address). Instead of symlinking the latest certs to the 'live' directory, `acme-issue` will now copy the files (this improves compatiblity with ionotify). The renewal script can now retry if a renewal failed earlier. Last but not least, the documentation was rewritten from scratch (there's a 'README.md' now) and some parts of the scripts were streamlined.

There's an unreleased version 1.7 in between we're skipping now. Version 1.7 was used internally only and just for a couple of months. It was pretty much tied to a single setup, so it's not really worth releasing this.

diff --git a/src/acme-issue b/src/acme-issue
--- a/src/acme-issue
+++ b/src/acme-issue
@@ -1,6 +1,6 @@
 #!/bin/bash
-# Issue Let's Encrypt SSL certificates using acme-tiny
-# Version 1.6 (build 20200919)
+# Issue Let's Encrypt TLS certificate using acme-tiny
+# Version 1.8 (build 20211002)
 #
 # Copyright (c) 2016-2021  Daniel Rudolf <www.daniel-rudolf.de>
 #
@@ -11,48 +11,50 @@
 # License-Filename: LICENSE
 
 APP_NAME="$(basename "$0")"
+APP_PATH="/var/local/acme"
+CONFIG_PATH="/etc/acme"
+
+VERSION="1.8"
+BUILD="20211002"
+
 set -e
+umask 022
 
-VERSION="1.6"
-BUILD="20200919"
-
-if [ "$(id -u)" != "0" ]; then
-    echo "$APP_NAME: You must run this as root" >&2
-    exit 1
-elif [ "$(sudo -u acme -- id -un)" != "acme" ]; then
-    echo "$APP_NAME: User 'acme' not found or not sudo-able" >&2
-    exit 1
-elif [ ! -d "/etc/ssl/acme" ]; then
-    echo "$APP_NAME: Base directory '/etc/ssl/acme' not found" >&2
-    exit 1
-elif [ ! -x "$(which acme-tiny)" ]; then
-    echo "$APP_NAME: 'acme-tiny' executable not found" >&2
-    exit 1
-fi
-
-function showUsage() {
+show_usage() {
     echo "Usage:"
     echo "  $APP_NAME [--force] DOMAIN_NAME [DOMAIN_ALIAS...]"
     echo "  $APP_NAME --renew DOMAIN_NAME"
 }
 
 # read parameters
-RENEW="no"
-FORCE="no"
 DOMAIN=""
 DOMAIN_ALIASES=()
+RENEW="no"
+FORCE="no"
 while [ $# -gt 0 ]; do
+    if [[ "$1" =~ ^-[a-zA-Z0-9]{2,}$ ]]; then
+        read -a SHORT_OPTS <<< $(echo "${1:1}" | sed 's/./-& /g')
+        set -- "${SHORT_OPTS[@]}" "${@:2}"
+        continue
+    fi
+
     if [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
-        showUsage
+        show_usage
         echo
         echo "Options:"
-        echo "  -r, --renew   renew a existing certificate"
-        echo "  -f, --force   issue a new certificate even though there is another"
-        echo "                certificate for this DOMAIN_NAME"
+        echo "  -r, --renew  renew an existing certificate"
+        echo "  -f, --force  issue a new certificate even though there is another"
+        echo "               certificate for this DOMAIN_NAME"
         echo
         echo "Help options:"
-        echo "  -h, --help      display this help and exit"
-        echo "      --version   output version information and exit"
+        echo "  -h, --help     display this help and exit"
+        echo "      --version  output version information and exit"
+        echo
+        echo "Environment:"
+        echo "  ACME_ACCOUNT_KEY_FILE  path to your ACME account private key"
+        echo "  ACME_ACCOUNT_CONTACT   contact details for your account"
+        echo "  ACME_DIRECTORY_URL     ACME directory URL of the CA to use"
+        echo "  TLS_KEY_GROUP          associated group for TLS key files"
         exit 0
     elif [ "$1" == "--version" ]; then
         echo "acme-issue $VERSION ($BUILD)"
@@ -76,21 +78,49 @@ while [ $# -gt 0 ]; do
     shift
 done
 
-if [ -z "$DOMAIN" ]; then
+# check parameters and runtime requirements
+if [ "$(id -un)" != "acme" ]; then
+    echo "$APP_NAME: You must run this as user 'acme'" >&2
+    exit 1
+elif [ ! -d "$APP_PATH" ]; then
+    echo "$APP_NAME: Base directory '$APP_PATH' not found" >&2
+    exit 1
+elif [ ! -d "$CONFIG_PATH" ]; then
+    echo "$APP_NAME: Config directory '$CONFIG_PATH' not found" >&2
+    exit 1
+elif [ ! -x "$(which openssl)" ]; then
+    echo "$APP_NAME: 'openssl' executable not found" >&2
+    exit 1
+elif [ ! -x "$(which acme-tiny)" ]; then
+    echo "$APP_NAME: 'acme-tiny' executable not found" >&2
+    exit 1
+elif [ -z "$DOMAIN" ]; then
     echo "$APP_NAME: You must pass a DOMAIN_NAME" >&2
-    showUsage
+    show_usage
+    exit 1
+fi
+
+# include config file
+if [ -f "$CONFIG_PATH/config.env" ]; then
+    . "$CONFIG_PATH/config.env"
+fi
+
+# check account key
+ACME_ACCOUNT_KEY_FILE="${ACME_ACCOUNT_KEY_FILE:-$CONFIG_PATH/account.key}"
+if [ ! -e "$ACME_ACCOUNT_KEY_FILE" ]; then
+    echo "$APP_NAME: Invalid account key '$ACME_ACCOUNT_KEY_FILE': No such file or directory" >&2
     exit 1
 fi
 
 # check target directory
 if [ "$RENEW" == "no" ]; then
-    if [ -d "/etc/ssl/acme/archive/$DOMAIN" ] && [ "$FORCE" == "no" ]; then
-        echo "$APP_NAME: Conflicting target directory '/etc/ssl/acme/archive/$DOMAIN' found" >&2
+    if [ -d "$APP_PATH/archive/$DOMAIN" ] && [ "$FORCE" == "no" ]; then
+        echo "$APP_NAME: Conflicting target directory '$APP_PATH/archive/$DOMAIN' found" >&2
         echo "$APP_NAME: Use --force to suppress this error" >&2
         exit 1
     fi
 else
-    if [ ! -d "/etc/ssl/acme/live/$DOMAIN" ]; then
+    if [ ! -d "$APP_PATH/live/$DOMAIN" ]; then
         echo "$APP_NAME: No certificate to renew found" >&2
         exit 1
     fi
@@ -110,7 +140,7 @@ else
         exit 1
     fi
 
-    SAN="$(openssl x509 -noout -text -in "/etc/ssl/acme/live/$DOMAIN/cert.pem" \
+    SAN="$(openssl x509 -noout -text -in "$APP_PATH/live/$DOMAIN/cert.pem" \
         | awk '/X509v3 Subject Alternative Name/ {getline; sub(/^[ \t]+/, ""); sub(/[ \t]+$/, ""); print}')"
 fi
 
@@ -121,90 +151,87 @@ exec 3> >(sed 's/^/    /g')
 echo "Preparing target directory..."
 
 DATE="$(date --utc +'%FT%TZ')"
-sudo -u acme -- mkdir -p "/etc/ssl/acme/archive/$DOMAIN/$DATE"
+mkdir -p "$APP_PATH/archive/$DOMAIN/$DATE"
 
-# generate private key (requires root)
+# generate private key
 echo "Generating private key..."
 
-( umask 027 && openssl genrsa -out "/etc/ssl/acme/archive/$DOMAIN/$DATE/key.pem" 4096 2>&3 )
-chmod 640 "/etc/ssl/acme/archive/$DOMAIN/$DATE/key.pem"
-chown root:ssl-cert "/etc/ssl/acme/archive/$DOMAIN/$DATE/key.pem"
+( umask 027 && openssl genrsa -out "$APP_PATH/archive/$DOMAIN/$DATE/key.pem" 4096 2>&3 )
+chmod 640 "$APP_PATH/archive/$DOMAIN/$DATE/key.pem"
+[ -z "$TLS_KEY_GROUP" ] || chgrp "$TLS_KEY_GROUP" "$APP_PATH/archive/$DOMAIN/$DATE/key.pem"
 
-if ! openssl rsa -in "/etc/ssl/acme/archive/$DOMAIN/$DATE/key.pem" -check -noout > /dev/null 2>&1; then
-    echo "$APP_NAME: Invalid private key '/etc/ssl/acme/archive/$DOMAIN/$DATE/key.pem'" >&2
+if ! openssl rsa -in "$APP_PATH/archive/$DOMAIN/$DATE/key.pem" -check -noout > /dev/null 2>&1; then
+    echo "$APP_NAME: Invalid private key '$APP_PATH/archive/$DOMAIN/$DATE/key.pem'" >&2
     exit 1
 fi
 
 # create CSR
 echo "Creating CSR..."
 
-OPENSSL_CONFIG="$(sudo -u acme -- mktemp)"
-cat "/etc/ssl/openssl.cnf" <(printf "[SAN]\nsubjectAltName=$SAN\n") \
-    | sudo -u acme -- tee "$OPENSSL_CONFIG" > /dev/null
+OPENSSL_CONFIG="$(mktemp)"
+cat "/etc/ssl/openssl.cnf" <(printf "[SAN]\nsubjectAltName=%s\n" "$SAN") \
+    > "$OPENSSL_CONFIG"
 
-sudo -u acme -- openssl req -new -sha256 \
-    -key "/etc/ssl/acme/archive/$DOMAIN/$DATE/key.pem" \
+openssl req -new -sha256 \
+    -key "$APP_PATH/archive/$DOMAIN/$DATE/key.pem" \
     -subj "/" -reqexts SAN -config "$OPENSSL_CONFIG" \
-    -out "/etc/ssl/acme/archive/$DOMAIN/$DATE/csr.pem"
+    -out "$APP_PATH/archive/$DOMAIN/$DATE/csr.pem"
 
-sudo -u acme -- rm "$OPENSSL_CONFIG"
+rm "$OPENSSL_CONFIG"
 
-if ! openssl req -in "/etc/ssl/acme/archive/$DOMAIN/$DATE/csr.pem" -verify -noout > /dev/null 2>&1; then
-    echo "$APP_NAME: Invalid CSR '/etc/ssl/acme/archive/$DOMAIN/$DATE/csr.pem'" >&2
+if ! openssl req -in "$APP_PATH/archive/$DOMAIN/$DATE/csr.pem" -verify -noout > /dev/null 2>&1; then
+    echo "$APP_NAME: Invalid CSR '$APP_PATH/archive/$DOMAIN/$DATE/csr.pem'" >&2
     exit 1
 fi
 
 # issue certificate using acme-tiny
 echo "Issuing certificate..."
 
-sudo -u acme -- acme-tiny \
-    --account-key "/etc/ssl/acme/account.key" \
-    --csr "/etc/ssl/acme/archive/$DOMAIN/$DATE/csr.pem" \
-    --acme-dir "/etc/ssl/acme/challenges" \
-    --disable-check 2>&3 \
-    | sudo -u acme -- tee "/etc/ssl/acme/archive/$DOMAIN/$DATE/fullchain.pem" > /dev/null
+ACME_OPTIONS=( --account-key "$ACME_ACCOUNT_KEY_FILE" )
+[ -z "$ACME_ACCOUNT_CONTACT" ] || ACME_OPTIONS+=( --contact "$ACME_ACCOUNT_CONTACT" )
+[ -z "$ACME_DIRECTORY_URL" ] || ACME_OPTIONS+=( --directory-url "$ACME_DIRECTORY_URL" )
 
-if ! openssl x509 -in "/etc/ssl/acme/archive/$DOMAIN/$DATE/fullchain.pem" -noout > /dev/null 2>&1; then
-    echo "$APP_NAME: Invalid certificate chain '/etc/ssl/acme/archive/$DOMAIN/$DATE/fullchain.pem'" >&2
+acme-tiny \
+    --csr "$APP_PATH/archive/$DOMAIN/$DATE/csr.pem" \
+    --acme-dir "$APP_PATH/challenges" \
+    --disable-check \
+    "${ACME_OPTIONS[@]}" 2>&3 \
+    > "$APP_PATH/archive/$DOMAIN/$DATE/fullchain.pem"
+
+if ! openssl x509 -in "$APP_PATH/archive/$DOMAIN/$DATE/fullchain.pem" -noout > /dev/null 2>&1; then
+    echo "$APP_NAME: Invalid certificate chain '$APP_PATH/archive/$DOMAIN/$DATE/fullchain.pem'" >&2
     exit 1
 fi
 
 # split fullchain.pem into cert.pem and chain.pem
 echo "Splitting certificate chain..."
 
-SPLIT_FILE=""
-SPLIT_MATCH="no"
-while IFS= read -r SPLIT_LINE; do
-    if [ "$SPLIT_LINE" == "-----BEGIN CERTIFICATE-----" ]; then
-        [ -z "$SPLIT_FILE" ] && SPLIT_FILE="cert.pem" || SPLIT_FILE="chain.pem"
-        SPLIT_MATCH="yes"
-    fi
+awk -v out_dir="$APP_PATH/archive/$DOMAIN/$DATE/" -v out_file="cert.pem" \
+    -e '/^-----BEGIN CERTIFICATE-----$/{cert=1}' \
+    -e 'cert{print > out_dir out_file}' \
+    -e '/^-----END CERTIFICATE-----$/{cert=0; out_file="chain.pem"}' \
+    -- "$APP_PATH/archive/$DOMAIN/$DATE/fullchain.pem"
 
-    if [ "$SPLIT_MATCH" == "yes" ]; then
-        echo "$SPLIT_LINE" | sudo -u acme -- tee -a "/etc/ssl/acme/archive/$DOMAIN/$DATE/$SPLIT_FILE" > /dev/null
-    fi
-
-    if [ "$SPLIT_LINE" == "-----END CERTIFICATE-----" ]; then
-        SPLIT_MATCH="no"
-    fi
-done < "/etc/ssl/acme/archive/$DOMAIN/$DATE/fullchain.pem"
-
-if ! openssl x509 -in "/etc/ssl/acme/archive/$DOMAIN/$DATE/cert.pem" -noout > /dev/null 2>&1; then
-    echo "$APP_NAME: Invalid certificate '/etc/ssl/acme/archive/$DOMAIN/$DATE/cert.pem'" >&2
+if ! openssl x509 -in "$APP_PATH/archive/$DOMAIN/$DATE/cert.pem" -noout > /dev/null 2>&1; then
+    echo "$APP_NAME: Invalid certificate '$APP_PATH/archive/$DOMAIN/$DATE/cert.pem'" >&2
     exit 1
 fi
 
-if [ ! -e "/etc/ssl/acme/archive/$DOMAIN/$DATE/chain.pem" ]; then
-    sudo -u acme -- touch "/etc/ssl/acme/archive/$DOMAIN/$DATE/chain.pem"
-elif ! openssl x509 -in "/etc/ssl/acme/archive/$DOMAIN/$DATE/chain.pem" -noout > /dev/null 2>&1; then
-    echo "$APP_NAME: Invalid intermediate certificate(s) '/etc/ssl/acme/archive/$DOMAIN/$DATE/chain.pem'" >&2
+if [ ! -e "$APP_PATH/archive/$DOMAIN/$DATE/chain.pem" ]; then
+    touch "$APP_PATH/archive/$DOMAIN/$DATE/chain.pem"
+elif ! openssl x509 -in "$APP_PATH/archive/$DOMAIN/$DATE/chain.pem" -noout > /dev/null 2>&1; then
+    echo "$APP_NAME: Invalid intermediate certificate(s) '$APP_PATH/archive/$DOMAIN/$DATE/chain.pem'" >&2
     exit 1
 fi
 
-# symlink target dir to live dir
+# copy files to live dir (deployment)
 echo "Deploying certificate..."
-[ -h "/etc/ssl/acme/live/$DOMAIN" ] && sudo -u acme -- rm "/etc/ssl/acme/live/$DOMAIN"
-sudo -u acme -- ln -s "/etc/ssl/acme/archive/$DOMAIN/$DATE/" "/etc/ssl/acme/live/$DOMAIN"
+[ -d "$APP_PATH/live/$DOMAIN" ] || mkdir "$APP_PATH/live/$DOMAIN"
+cp "$APP_PATH/archive/$DOMAIN/$DATE/key.pem" \
+    "$APP_PATH/archive/$DOMAIN/$DATE/cert.pem" \
+    "$APP_PATH/archive/$DOMAIN/$DATE/chain.pem" \
+    "$APP_PATH/archive/$DOMAIN/$DATE/fullchain.pem" \
+    "$APP_PATH/live/$DOMAIN/"
 
 exec 3>&-
 exit 0
diff --git a/src/acme-renew b/src/acme-renew
--- a/src/acme-renew
+++ b/src/acme-renew
@@ -1,6 +1,6 @@
 #!/bin/bash
-# Renew Let's Encrypt SSL certificates using acme-tiny
-# Version 1.6 (build 20200919)
+# Renew Let's Encrypt TLS certificates using acme-tiny
+# Version 1.8 (build 20211002)
 #
 # Copyright (c) 2016-2021  Daniel Rudolf <www.daniel-rudolf.de>
 #
@@ -11,40 +11,50 @@
 # License-Filename: LICENSE
 
 APP_NAME="$(basename "$0")"
+APP_PATH="/var/local/acme"
+
+VERSION="1.8"
+BUILD="20211002"
+
 set -e
 
-VERSION="1.6"
-BUILD="20200919"
-
-if [ ! -d "/etc/ssl/acme" ]; then
-    echo "$APP_NAME: Base directory '/etc/ssl/acme' not found" >&2
-    exit 1
-elif [ ! -x "$(which acme-issue)" ]; then
-    echo "$APP_NAME: 'acme-issue' executable not found" >&2
-    exit 1
-fi
-
-function showUsage() {
+show_usage() {
     echo "Usage:"
-    echo "  $APP_NAME --all"
-    echo "  $APP_NAME DOMAIN_NAME..."
+    echo "  $APP_NAME [--verbose|--quiet] [--retry...] --all"
+    echo "  $APP_NAME [--verbose|--quiet] [--retry...] DOMAIN_NAME..."
 }
 
 # read parameters
-VERBOSE="no"
 DOMAINS=()
+ALL_DOMAINS="no"
+RETRY=0
+VERBOSE="no"
+QUIET="no"
 while [ $# -gt 0 ]; do
+    if [[ "$1" =~ ^-[a-zA-Z0-9]{2,}$ ]]; then
+        read -a SHORT_OPTS <<< $(echo "${1:1}" | sed 's/./-& /g')
+        set -- "${SHORT_OPTS[@]}" "${@:2}"
+        continue
+    fi
+
     if [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
-        showUsage
+        show_usage
         echo
         echo "Options:"
-        echo "  -a, --all       renew all certificates"
-        echo "  -v, --verbose   explain what is being done"
-        echo "  -q, --quiet     suppress status information"
+        echo "  -a, --all      renew all certificates"
+        echo "  -r, --retry    retry if renewal fails"
+        echo "  -v, --verbose  explain what is being done"
+        echo "  -q, --quiet    suppress status information"
         echo
         echo "Help options:"
-        echo "  -h, --help      display this help and exit"
-        echo "      --version   output version information and exit"
+        echo "  -h, --help     display this help and exit"
+        echo "      --version  output version information and exit"
+        echo
+        echo "Environment:"
+        echo "  ACME_ACCOUNT_KEY_FILE  path to your ACME account private key"
+        echo "  ACME_ACCOUNT_CONTACT   contact details for your account"
+        echo "  ACME_DIRECTORY_URL     ACME directory URL of the CA to use"
+        echo "  TLS_KEY_GROUP          associated group for TLS key files"
         exit 0
     elif [ "$1" == "--version" ]; then
         echo "acme-renew $VERSION ($BUILD)"
@@ -55,15 +65,14 @@ while [ $# -gt 0 ]; do
         echo
         echo "Written by Daniel Rudolf <https://www.daniel-rudolf.de/>"
         exit 0
+    elif [ "$1" == "--all" ] || [ "$1" == "-a" ]; then
+        ALL_DOMAINS="yes"
+    elif [ "$1" == "--retry" ] || [ "$1" == "-r" ]; then
+        (( ++RETRY ))
     elif [ "$1" == "--verbose" ] || [ "$1" == "-v" ]; then
         VERBOSE="yes"
     elif [ "$1" == "--quiet" ] || [ "$1" == "-q" ]; then
-        # pipe stdout to /dev/null
-        exec 1> /dev/null
-    elif [ "$1" == "--all" ] || [ "$1" == "-a" ]; then
-        while IFS="" read -r -u 4 -d $'\0' DOMAIN; do
-            DOMAINS+=( "$DOMAIN" )
-        done 4< <(find /etc/ssl/acme/live/ -mindepth 1 -printf "%f\0")
+        QUIET="yes"
     else
         DOMAINS+=( "$1" )
     fi
@@ -71,29 +80,84 @@ while [ $# -gt 0 ]; do
     shift
 done
 
-if [ ${#DOMAINS[@]} -eq 0 ]; then
-    echo "$APP_NAME: You must either pass --all or a DOMAIN_NAME" >&2
-    showUsage
+# check parameters and runtime requirements
+if [ "$(id -un)" != "acme" ]; then
+    echo "$APP_NAME: You must run this as user 'acme'" >&2
+    exit 1
+elif [ ! -d "$APP_PATH" ]; then
+    echo "$APP_NAME: Base directory '$APP_PATH' not found" >&2
+    exit 1
+elif [ ! -x "$(which acme-issue)" ]; then
+    echo "$APP_NAME: 'acme-issue' executable not found" >&2
+    exit 1
+elif [ ${#DOMAINS[@]} -eq 0 ]; then
+    echo "$APP_NAME: You must either pass a DOMAIN_NAME or --all" >&2
+    show_usage
     exit 1
 fi
 
+# apply parameters
+if [ "$QUIET" == "yes" ]; then
+    exec 1> /dev/null
+    exec 2> /dev/null
+fi
+
+if [ "$ALL_DOMAINS" == "yes" ]; then
+    while IFS="" read -r -u 3 -d $'\0' DOMAIN_PATH; do
+        DOMAINS+=( "$(basename "$DOMAIN_PATH")" )
+    done 3< <(find "$APP_PATH/live/" -mindepth 1 -maxdepth 1 -type d -print0)
+fi
+
+# run acme-issue
 EXIT_CODE=0
 if [ "$VERBOSE" == "yes" ]; then
     for DOMAIN in "${DOMAINS[@]}"; do
-        echo "Renewing '$DOMAIN'..."
-        acme-issue --renew "$DOMAIN" || { EXIT_CODE=$?; true; }
-    done
+        for (( RETRY_COUNT=0 ; RETRY_COUNT <= RETRY ; RETRY_COUNT++ )); do
+            [ $RETRY_COUNT -eq 0 ] \
+                && echo "Renewing '$DOMAIN'..." \
+                || echo "Retrying renewal of '$DOMAIN' in 60 seconds..."
 
-    if [ $EXIT_CODE -ne 0 ]; then
-        echo "$APP_NAME: Renewal of one or more domains failed" >&2
-    fi
+            [ $RETRY_COUNT -eq 0 ] || sleep 60
+
+            DOMAIN_STATUS=0
+            acme-issue --renew "$DOMAIN" \
+                || { DOMAIN_STATUS=$?; true; }
+
+            if [ $DOMAIN_STATUS -eq 0 ]; then
+                echo "Successfully renewed '$DOMAIN'"
+                break
+            fi
+
+            echo "Renewal of '$DOMAIN' failed"
+            EXIT_CODE=$DOMAIN_STATUS
+        done
+    done
 else
     for DOMAIN in "${DOMAINS[@]}"; do
-        echo -n "Renewing '$DOMAIN'..."
-        acme-issue --renew "$DOMAIN" > /dev/null \
-            && { echo " success"; } \
-            || { echo " failed"; EXIT_CODE=$?; true; }
+        for (( RETRY_COUNT=0 ; RETRY_COUNT <= RETRY ; RETRY_COUNT++ )); do
+            [ $RETRY_COUNT -eq 0 ] \
+                && echo -n "Renewing '$DOMAIN'..." \
+                || echo -n "Retrying '$DOMAIN'..."
+
+            [ $RETRY_COUNT -eq 0 ] || sleep 60
+
+            DOMAIN_STATUS=0
+            acme-issue --renew "$DOMAIN" > /dev/null 2>&1 \
+                || { DOMAIN_STATUS=$?; true; }
+
+            if [ $DOMAIN_STATUS -eq 0 ]; then
+                echo " success"
+                break
+            fi
+
+            echo " failed"
+            EXIT_CODE=$DOMAIN_STATUS
+        done
     done
+fi
+
+if [ $EXIT_CODE -ne 0 ] && [ "$VERBOSE" == "yes" ]; then
+    echo "$APP_NAME: Renewal of one or more domains failed" >&2
 fi
 
 exit $EXIT_CODE
