Fix `acme-renew --all` complaining about no domains

diff --git a/src/acme-renew b/src/acme-renew
--- a/src/acme-renew
+++ b/src/acme-renew
@@ -90,7 +90,7 @@ elif [ ! -d "$APP_PATH" ]; then
 elif [ ! -x "$(which acme-issue)" ]; then
     echo "$APP_NAME: 'acme-issue' executable not found" >&2
     exit 1
-elif [ ${#DOMAINS[@]} -eq 0 ]; then
+elif [ ${#DOMAINS[@]} -eq 0 ] && [ "$ALL_DOMAINS" == "no" ]; then
     echo "$APP_NAME: You must either pass a DOMAIN_NAME or --all" >&2
     show_usage
     exit 1
@@ -111,6 +111,11 @@ fi
 # run acme-issue
 EXIT_CODE=0
 if [ "$VERBOSE" == "yes" ]; then
+    if [ ${#DOMAINS[@]} -eq 0 ]; then
+        echo "No domains to renew, exiting..."
+        exit
+    fi
+
     for DOMAIN in "${DOMAINS[@]}"; do
         for (( RETRY_COUNT=0 ; RETRY_COUNT <= RETRY ; RETRY_COUNT++ )); do
             [ $RETRY_COUNT -eq 0 ] \
@@ -132,6 +137,10 @@ if [ "$VERBOSE" == "yes" ]; then
             EXIT_CODE=$DOMAIN_STATUS
         done
     done
+
+    if [ $EXIT_CODE -ne 0 ]; then
+        echo "$APP_NAME: Renewal of one or more domains failed" >&2
+    fi
 else
     for DOMAIN in "${DOMAINS[@]}"; do
         for (( RETRY_COUNT=0 ; RETRY_COUNT <= RETRY ; RETRY_COUNT++ )); do
@@ -154,10 +163,6 @@ else
             EXIT_CODE=$DOMAIN_STATUS
         done
     done
-fi
-
-if [ $EXIT_CODE -ne 0 ] && [ "$VERBOSE" == "yes" ]; then
-    echo "$APP_NAME: Renewal of one or more domains failed" >&2
 fi
 
 exit $EXIT_CODE
